#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL="${RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL:-jointpos-reachable-jointlimit-guard-rotpolish-probe}"

# Continue from the soft-gated insertion run: keep bounded Z progress, but once
# XY/depth/contact are ready, hold a small preload and spend the remaining budget
# repairing orientation instead of letting late insertion drift sideways.
export RCA_LAUNCHABLE_SCRIPTED_STEPS="${RCA_LAUNCHABLE_SCRIPTED_STEPS:-2600}"
export RCA_LAUNCHABLE_TIMEOUT_SECONDS="${RCA_LAUNCHABLE_TIMEOUT_SECONDS:-3900}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH:-1}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_XY_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_XY_TOL:-0.006}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_Z_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_Z_TOL:-0.050}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_CONTACT_MIN_FORCE="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_CONTACT_MIN_FORCE:-0.5}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_XY_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_XY_TOL:-0.012}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_Z_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_Z_TOL:-0.060}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_PRELOAD_STEP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_PRELOAD_STEP:-0.001}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_STEP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_STEP:-0.035}"

exec "${SCRIPT_DIR}/run_launchable_phase2_jointpos_reachable_guard_softgated_probe.sh" "$@"
