#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_GATE_COMMAND="probe_only"
export RCA_GATE_PROFILE="${RCA_GATE_PROFILE:-cheap}"
export RCA_GATE_INSTANCE_NAME="${RCA_GATE_INSTANCE_NAME:-isaac-probe-direct-ssh-l4}"
export RCA_GATE_CREATE_TIMEOUT="${RCA_GATE_CREATE_TIMEOUT:-600}"
export RCA_GATE_READY_TIMEOUT_SECONDS="${RCA_GATE_READY_TIMEOUT_SECONDS:-240}"
export RCA_GATE_BUILD_STUCK_SECONDS="${RCA_GATE_BUILD_STUCK_SECONDS:-30}"
export RCA_GATE_DELETE_TIMEOUT_SECONDS="${RCA_GATE_DELETE_TIMEOUT_SECONDS:-900}"
export RCA_GATE_DIRECT_SSH_AFTER_CREATE_READY="${RCA_GATE_DIRECT_SSH_AFTER_CREATE_READY:-1}"
export RCA_GATE_DIRECT_SSH_PROBE_ATTEMPTS="${RCA_GATE_DIRECT_SSH_PROBE_ATTEMPTS:-12}"
export RCA_GATE_DIRECT_SSH_PROBE_INTERVAL_SECONDS="${RCA_GATE_DIRECT_SSH_PROBE_INTERVAL_SECONDS:-10}"
export RCA_GATE_SSH_CONNECT_TIMEOUT="${RCA_GATE_SSH_CONNECT_TIMEOUT:-20}"
export RCA_GATE_SSH_COMMAND_TIMEOUT="${RCA_GATE_SSH_COMMAND_TIMEOUT:-60}"

exec "${SCRIPT_DIR}/run_guarded_phase2_gate.sh"
