#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL="${RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL:-jointpos-reachable-approach-probe}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH="${RCA_LAUNCHABLE_REACHABLE_APPROACH:-1}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_START_RADIUS="${RCA_LAUNCHABLE_REACHABLE_APPROACH_START_RADIUS:-0.060}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_MIN_RADIUS="${RCA_LAUNCHABLE_REACHABLE_APPROACH_MIN_RADIUS:-0.000}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_STEP="${RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_STEP:-0.002}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_XY_TOL="${RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_XY_TOL:-0.015}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_JOINT_MARGIN_MIN="${RCA_LAUNCHABLE_REACHABLE_APPROACH_JOINT_MARGIN_MIN:-0.080}"

# Isolate the target-generation change by default; callers can explicitly re-enable nullspace bias.
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN:-0.000}"

exec "${SCRIPT_DIR}/run_launchable_phase2_jointpos_nullspace_probe.sh" "$@"
