#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL="${RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL:-jointpos-reachable-jointlimit-guard-tuned-probe}"

# Keep the proven reachable-approach setup, but relax the late guard so insertion can
# continue after the first strong-guard probe preserved too much joint4 margin.
export RCA_LAUNCHABLE_SCRIPTED_STEPS="${RCA_LAUNCHABLE_SCRIPTED_STEPS:-2000}"
export RCA_LAUNCHABLE_TIMEOUT_SECONDS="${RCA_LAUNCHABLE_TIMEOUT_SECONDS:-3000}"
export RCA_LAUNCHABLE_INSERT_JOINT_LIMIT_MARGIN="${RCA_LAUNCHABLE_INSERT_JOINT_LIMIT_MARGIN:-0.060}"

export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN:-0.050}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_ACTIVATION_MARGIN="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_ACTIVATION_MARGIN:-0.350}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_STEP="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_STEP:-0.040}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_DAMPING="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_DAMPING:-0.075}"

export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_GAIN="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_GAIN:-0.060}"
export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_ACTIVATION_MARGIN="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_ACTIVATION_MARGIN:-0.110}"
export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_STEP="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_STEP:-0.040}"

exec "${SCRIPT_DIR}/run_launchable_phase2_jointpos_reachable_guard_probe.sh" "$@"
