#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL="${RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL:-jointpos-reachable-jointlimit-guard-adaptive-rotpolish-probe}"

# Follow-up to the 2026-06-08 rotpolish run. The first depth polish preserved XY/Z
# but pushed rotation into a worse branch. This variant uses a persistent quaternion
# waypoint and exits when contact drops, so late rotation only advances while depth
# and contact remain stable.
export RCA_LAUNCHABLE_SCRIPTED_STEPS="${RCA_LAUNCHABLE_SCRIPTED_STEPS:-3000}"
export RCA_LAUNCHABLE_TIMEOUT_SECONDS="${RCA_LAUNCHABLE_TIMEOUT_SECONDS:-4500}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH:-1}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ORIENTATION_MODE="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ORIENTATION_MODE:-stateful-waypoint}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_XY_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_XY_TOL:-0.006}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_Z_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_Z_TOL:-0.050}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_CONTACT_MIN_FORCE="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_CONTACT_MIN_FORCE:-0.5}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_CONTACT_MIN_FORCE="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_CONTACT_MIN_FORCE:-0.30}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_XY_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_XY_TOL:-0.010}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_Z_TOL="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_EXIT_Z_TOL:-0.055}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_PRELOAD_STEP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_PRELOAD_STEP:-0.0005}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_STEP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_STEP:-0.012}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_POS_GAIN="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_POS_GAIN:-0.8}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_POS_CLAMP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_POS_CLAMP:-0.003}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_GAIN="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_GAIN:-2.0}"
export RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_CLAMP="${RCA_LAUNCHABLE_DEPTH_ROTATION_POLISH_ROT_CLAMP:-0.08}"

exec "${SCRIPT_DIR}/run_launchable_phase2_jointpos_reachable_guard_softgated_probe.sh" "$@"
