#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ENV_NAME="${1:-isaac-l40s}"
REMOTE_ROOT="${2:-/home/ubuntu/projects/robot-contact-assembly}"
COMPOSE_ROOT="${3:-/home/ubuntu/isaac-compose}"
TASK_NAME="${4:-RCA-PegInHole-Franka-JointPos-Contact-Play-v0}"
NUM_ENVS="${5:-1}"
STEPS="${6:-1200}"
SEED="${7:-42}"

CALIBRATION_STEPS_PER_PROBE="${RCA_JOINT_RESPONSE_SOCKET_CALIBRATION_STEPS_PER_PROBE:-8}"
CALIBRATION_TIMEOUT_SECONDS="${RCA_JOINT_RESPONSE_SOCKET_CALIBRATION_TIMEOUT_SECONDS:-900}"
SUMMARY_PATH="/workspace/artifacts/calibration/joint_position_action/latest_seed_${SEED}.json"

echo "[joint-response-socket] calibrating empirical JointPositionAction response"
"${SCRIPT_DIR}/run_remote_joint_response_calibration.sh" \
  "${ENV_NAME}" \
  "${REMOTE_ROOT}" \
  "${COMPOSE_ROOT}" \
  "${TASK_NAME}" \
  "${CALIBRATION_STEPS_PER_PROBE}" \
  "${SEED}" \
  "${CALIBRATION_TIMEOUT_SECONDS}"

JOINT_RESPONSE_ARGS=(
  --joint-response-json "${SUMMARY_PATH}"
  --joint-response-damping "${RCA_JOINT_RESPONSE_DAMPING:-0.0001}"
  --joint-response-max-delta "${RCA_JOINT_RESPONSE_MAX_DELTA:-0.04}"
  --socket-insertion-servo-rotate-only-when-rot-misaligned
  --success-hold-steps "${RCA_JOINT_RESPONSE_SOCKET_SUCCESS_HOLD_STEPS:-5}"
  --trace-autoflush-every "${RCA_JOINT_RESPONSE_SOCKET_TRACE_AUTOFLUSH_EVERY:-1}"
)

if [[ -n "${RCA_JOINT_RESPONSE_SOCKET_EXTRA_AGENT_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  EXTRA_JOINT_RESPONSE_ARGS=(${RCA_JOINT_RESPONSE_SOCKET_EXTRA_AGENT_ARGS})
  JOINT_RESPONSE_ARGS+=("${EXTRA_JOINT_RESPONSE_ARGS[@]}")
fi

if [[ -n "${RCA_SOCKET_INSERTION_SERVO_EXTRA_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  EXISTING_SOCKET_EXTRA_ARGS=(${RCA_SOCKET_INSERTION_SERVO_EXTRA_ARGS})
  JOINT_RESPONSE_ARGS+=("${EXISTING_SOCKET_EXTRA_ARGS[@]}")
fi

echo "[joint-response-socket] running metric-tip socket insertion with ${SUMMARY_PATH}"
RCA_VALIDATE_ACTION_RESPONSE="${RCA_JOINT_RESPONSE_SOCKET_VALIDATE_ACTION_RESPONSE:-1}" \
RCA_VALIDATE_FINAL_CONTACT_BOUNDARY="${RCA_JOINT_RESPONSE_SOCKET_VALIDATE_FINAL_CONTACT_BOUNDARY:-1}" \
RCA_VALIDATE_PEG_VIDEO_CANDIDATE="${RCA_JOINT_RESPONSE_SOCKET_VALIDATE_PEG_VIDEO_CANDIDATE:-1}" \
RCA_VALIDATE_TRACE_FRAME_ALIGNMENT="${RCA_JOINT_RESPONSE_SOCKET_VALIDATE_TRACE_FRAME_ALIGNMENT:-1}" \
RCA_TRACE_ONLY_TIMEOUT_SECONDS="${RCA_JOINT_RESPONSE_SOCKET_TRACE_TIMEOUT_SECONDS:-900}" \
RCA_TRACE_ONLY_TIMEOUT_KILL_SECONDS="${RCA_JOINT_RESPONSE_SOCKET_TRACE_TIMEOUT_KILL_SECONDS:-30}" \
RCA_SOCKET_INSERTION_SERVO_CONTROL_MODE=joint-response \
RCA_SOCKET_INSERTION_SERVO_Z_STEP="${RCA_JOINT_RESPONSE_SOCKET_Z_STEP:-0.0005}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_PRELOAD_STEP="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_PRELOAD_STEP:-0.0002}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_BOUNDARY_MIN_FORCE="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_BOUNDARY_MIN_FORCE:-0.25}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_BOUNDARY_TOL="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_BOUNDARY_TOL:-0.0010}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_BOUNDARY_STEP="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_BOUNDARY_STEP:-0.00015}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_BOUNDARY_XY_GAIN="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_BOUNDARY_XY_GAIN:-0.15}" \
RCA_SOCKET_INSERTION_SERVO_CONTACT_BOUNDARY_XY_CLAMP="${RCA_JOINT_RESPONSE_SOCKET_CONTACT_BOUNDARY_XY_CLAMP:-0.00035}" \
RCA_SOCKET_INSERTION_SERVO_MAINTAIN_CONTACT_PRELOAD="${RCA_JOINT_RESPONSE_SOCKET_MAINTAIN_CONTACT_PRELOAD:-1}" \
RCA_SOCKET_INSERTION_SERVO_ROT_STEP="${RCA_JOINT_RESPONSE_SOCKET_ROT_STEP:-0.015}" \
RCA_ACTION_RESPONSE_MIN_COMMAND_NORM="${RCA_JOINT_RESPONSE_SOCKET_ACTION_RESPONSE_MIN_COMMAND_NORM:-0.0002}" \
RCA_ACTION_RESPONSE_STOP_AFTER_FIRST_SUCCESS="${RCA_JOINT_RESPONSE_SOCKET_ACTION_RESPONSE_STOP_AFTER_FIRST_SUCCESS:-1}" \
RCA_SOCKET_INSERTION_SERVO_EXTRA_ARGS="${JOINT_RESPONSE_ARGS[*]}" \
  "${SCRIPT_DIR}/run_remote_socket_insertion_servo_trace.sh" \
    "${ENV_NAME}" \
    "${REMOTE_ROOT}" \
    "${COMPOSE_ROOT}" \
    "${TASK_NAME}" \
    "${NUM_ENVS}" \
    "${STEPS}" \
    "${SEED}"

echo "[joint-response-socket] PASS: metric-tip socket insertion trace passed validators"
