#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL="${RCA_LAUNCHABLE_JOINTPOS_PROBE_LABEL:-jointpos-reachable-jointlimit-guard-probe}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH="${RCA_LAUNCHABLE_REACHABLE_APPROACH:-1}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_START_RADIUS="${RCA_LAUNCHABLE_REACHABLE_APPROACH_START_RADIUS:-0.060}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_MIN_RADIUS="${RCA_LAUNCHABLE_REACHABLE_APPROACH_MIN_RADIUS:-0.000}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_STEP="${RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_STEP:-0.002}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_XY_TOL="${RCA_LAUNCHABLE_REACHABLE_APPROACH_SHRINK_XY_TOL:-0.015}"
export RCA_LAUNCHABLE_REACHABLE_APPROACH_JOINT_MARGIN_MIN="${RCA_LAUNCHABLE_REACHABLE_APPROACH_JOINT_MARGIN_MIN:-0.080}"

export RCA_LAUNCHABLE_SCRIPTED_STEPS="${RCA_LAUNCHABLE_SCRIPTED_STEPS:-1600}"
export RCA_LAUNCHABLE_TIMEOUT_SECONDS="${RCA_LAUNCHABLE_TIMEOUT_SECONDS:-2400}"
export RCA_LAUNCHABLE_FAIL_CLOSED_EXIT_ZERO="${RCA_LAUNCHABLE_FAIL_CLOSED_EXIT_ZERO:-1}"
export RCA_LAUNCHABLE_JOINT_IK_STEP="${RCA_LAUNCHABLE_JOINT_IK_STEP:-0.30}"
export RCA_LAUNCHABLE_JOINT_STEP_LIMIT_MODE="${RCA_LAUNCHABLE_JOINT_STEP_LIMIT_MODE:-after-xy-global}"

# Preserve early reach freedom, then keep late insertion away from the joint4 lower-limit branch.
export RCA_LAUNCHABLE_JOINT_LIMIT_MARGIN="${RCA_LAUNCHABLE_JOINT_LIMIT_MARGIN:-0.020}"
export RCA_LAUNCHABLE_INSERT_JOINT_LIMIT_MARGIN="${RCA_LAUNCHABLE_INSERT_JOINT_LIMIT_MARGIN:-0.120}"

# The projected term should start before joint4 becomes critical; the hard guard is a late fallback.
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_GAIN:-0.080}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_ACTIVATION_MARGIN="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_ACTIVATION_MARGIN:-0.500}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_STEP="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_STEP:-0.050}"
export RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_DAMPING="${RCA_LAUNCHABLE_JOINT_LIMIT_NULLSPACE_DAMPING:-0.075}"
export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_GAIN="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_GAIN:-0.120}"
export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_ACTIVATION_MARGIN="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_ACTIVATION_MARGIN:-0.180}"
export RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_STEP="${RCA_LAUNCHABLE_JOINT_LIMIT_GUARD_STEP:-0.070}"

exec "${SCRIPT_DIR}/run_launchable_phase2_jointpos_nullspace_probe.sh" "$@"
